// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Door = (function(_super) {
    __extends(Door, _super);

    Door.COLOR_RED = 0;

    Door.COLOR_GREEN = 1;

    Door.COLOR_BLUE = 2;

    Door.ORIENTATION_LANDSCAPE = 3;

    Door.ORIENTATION_PORTRAIT = 4;

    function Door(x, y, collisionLayer, color, isOpen, orientation) {
      this.x = x;
      this.y = y;
      this.collisionLayer = collisionLayer;
      this.color = color;
      this.isOpen = isOpen;
      this.orientation = orientation;
      this.initialize();
    }

    Door.prototype.initialize = function() {
      var c, rectHeight, rectWidth;
      Door.__super__.initialize.apply(this, arguments);
      c = (function() {
        switch (this.color) {
          case this.constructor.COLOR_RED:
            return "#f00";
          case this.constructor.COLOR_GREEN:
            return "#0f0";
          case this.constructor.COLOR_BLUE:
            return "#00f";
        }
      }).call(this);
      if (this.orientation === this.constructor.ORIENTATION_LANDSCAPE) {
        rectWidth = 90;
        rectHeight = 10;
        this.x += 10;
        this.y -= 10;
      } else {
        rectWidth = 10;
        rectHeight = 90;
      }
      this.graphics.beginFill(c);
      this.graphics.drawRect(0, 0, rectWidth, rectHeight);
      this.hitBox = new createjs.Shape();
      this.hitBox.x = this.x;
      this.hitBox.y = this.y;
      this.hitBox.graphics.beginFill("#000");
      this.hitBox.graphics.drawRect(0, 0, rectWidth, rectHeight);
      return this.resetAppearance();
    };

    Door.prototype.toggleState = function() {
      this.isOpen = !this.isOpen;
      return this.resetAppearance();
    };

    Door.prototype.resetAppearance = function() {
      if (this.isOpen) {
        this.alpha = 0.3;
        return this.collisionLayer.removeChild(this.hitBox);
      } else {
        this.alpha = 1;
        return this.collisionLayer.addChild(this.hitBox);
      }
    };

    return Door;

  })(createjs.Shape);

}).call(this);
