// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Door = (function(_super) {
    __extends(Door, _super);

    function Door(x, y, levelWindow, color, isOpen, orientation) {
      this.x = x;
      this.y = y;
      this.levelWindow = levelWindow;
      this.color = color;
      this.isOpen = isOpen;
      this.orientation = orientation;
      this.initialize();
    }

    Door.prototype.initialize = function() {
      var c;
      Door.__super__.initialize.apply(this, arguments);
      c = (function() {
        switch (this.color) {
          case Color.RED:
            return "#f00";
          case Color.GREEN:
            return "#0f0";
          case Color.BLUE:
            return "#00f";
        }
      }).call(this);
      if (this.orientation === Orientation.LANDSCAPE) {
        this.rectWidth = 90;
        this.rectHeight = 10;
        this.x += 10;
        this.y -= 10;
      } else {
        this.rectWidth = 10;
        this.rectHeight = 90;
      }
      this.graphics.beginFill(c);
      this.graphics.drawRect(0, 0, this.rectWidth, this.rectHeight);
      return this.resetAppearance();
    };

    Door.prototype.toggleState = function() {
      this.isOpen = !this.isOpen;
      return this.resetAppearance();
    };

    Door.prototype.resetAppearance = function() {
      if (this.isOpen) {
        return this.alpha = 0.3;
      } else {
        return this.alpha = 1;
      }
    };

    return Door;

  })(createjs.Shape);

}).call(this);
