// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.RoomTrigger = (function(_super) {
    __extends(RoomTrigger, _super);

    function RoomTrigger(x, y, tweenDirection, unwatchFunction, levelWindow, playerLayer) {
      this.tweenDirection = tweenDirection;
      this.unwatchFunction = unwatchFunction;
      this.levelWindow = levelWindow;
      this.playerLayer = playerLayer;
      RoomTrigger.__super__.constructor.call(this, x, y, 8, 80);
    }

    RoomTrigger.prototype.setLinkedTrigger = function(linkedTrigger) {
      this.linkedTrigger = linkedTrigger;
    };

    RoomTrigger.prototype.startTransition = function() {
      var level, levelLayerTo, otherPlayer, player, playerLayerTo;
      player = this.playerLayer;
      otherPlayer = this.linkedTrigger.playerLayer;
      level = this.levelWindow.levelLayer;
      player.controlsMuted = true;
      this.unwatchFunction(this.levelWindow);
      levelLayerTo = level.x;
      levelLayerTo += this.tweenDirection === Direction.LEFT ? 700 : -700;
      playerLayerTo = player.x + 2 * (Player.WIDTH + 10);
      createjs.Tween.get(level).to({
        x: levelLayerTo
      }, 700).call(function() {
        return player.controlsMuted = false;
      });
      createjs.Tween.get(player).to({
        x: playerLayerTo
      }, 700);
      return createjs.Tween.get(otherPlayer).to({
        x: playerLayerTo
      }, 700);
    };

    RoomTrigger.prototype.onTick = function(e, data) {
      RoomTrigger.__super__.onTick.call(this, e, data);
      return data.trigger.isOnGround = data.player.yVelocity === 0;
    };

    return RoomTrigger;

  })(Trigger);

}).call(this);
