// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.TopRoomTrigger = (function(_super) {
    __extends(TopRoomTrigger, _super);

    function TopRoomTrigger() {
      return TopRoomTrigger.__super__.constructor.apply(this, arguments);
    }

    TopRoomTrigger.prototype.onTick = function(e, data) {
      var trigger;
      TopRoomTrigger.__super__.onTick.call(this, e, data);
      trigger = data.trigger;
      if (trigger.isTriggered && trigger.linkedTrigger.isTriggered && trigger.isOnGround && trigger.linkedTrigger.isOnGround) {
        return trigger.startTransition();
      }
    };

    return TopRoomTrigger;

  })(RoomTrigger);

}).call(this);
