// Generated by CoffeeScript 1.7.1
(function() {
  window.Preloader = {
    preload: function(filenames, onProgress, onFinished) {
      var filename, manifest, queue, _i, _len;
      queue = new createjs.LoadQueue(true, "/ld30/img/");
      manifest = [];
      for (_i = 0, _len = filenames.length; _i < _len; _i++) {
        filename = filenames[_i];
        manifest.push({
          id: filename,
          src: "" + filename + ".png"
        });
      }
      queue.on("progress", onProgress);
      queue.on("complete", onFinished);
      return queue.loadManifest(manifest);
    }
  };

}).call(this);
