// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.LevelGameWindow = (function(_super) {
    __extends(LevelGameWindow, _super);

    function LevelGameWindow(width, height, assetQueue) {
      this.assetQueue = assetQueue;
      LevelGameWindow.__super__.constructor.call(this, width, height);
    }

    LevelGameWindow.prototype.initialize = function() {
      LevelGameWindow.__super__.initialize.apply(this, arguments);
      this.doors = [];
      this.setupCollisionMap();
      this.setupPedestalBitmap();
      this.setupDoorLayer();
      this.drawDoorsToCollisionMap();
      this.setupPlayers();
      return this.setupForeground();
    };

    LevelGameWindow.prototype.setupCollisionMap = function() {
      var shape;
      shape = new createjs.Shape();
      this.collisionMap = shape;
      this.collisionMap.alpha = 0;
      return this.addChild(this.collisionMap);
    };

    LevelGameWindow.prototype.drawBaseCollisionMap = function(g) {
      g.beginFill("#000");
      g.moveTo(1010.0, 190.0);
      g.lineTo(1000.0, 190.0);
      g.lineTo(1000.0, 100.0);
      g.lineTo(1010.0, 100.0);
      g.lineTo(1010.0, 190.0);
      g.endFill();
      g.beginFill("#000");
      g.moveTo(1000.0, 200.0);
      g.lineTo(1070.0, 200.0);
      g.lineTo(1070.0, 190.0);
      g.lineTo(1000.0, 190.0);
      g.lineTo(1000.0, 200.0);
      g.endFill();
      g.beginFill("#000");
      g.moveTo(1000.0, 90.0);
      g.lineTo(1000.0, 100.0);
      g.lineTo(1110.0, 100.0);
      g.lineTo(1110.0, 90.0);
      g.lineTo(1000.0, 90.0);
      g.endFill();
      g.beginFill("#000");
      g.moveTo(1610.0, 500.0);
      g.lineTo(1500.0, 500.0);
      g.lineTo(1500.0, 490.0);
      g.lineTo(1610.0, 490.0);
      g.lineTo(1610.0, 500.0);
      g.endFill();
      g.beginFill("#000");
      g.moveTo(400.0, 90.0);
      g.lineTo(400.0, 100.0);
      g.lineTo(510.0, 100.0);
      g.lineTo(510.0, 90.0);
      g.lineTo(400.0, 90.0);
      g.endFill();
      g.beginFill("#000");
      g.moveTo(2090.0, 0.0);
      g.lineTo(2090.0, 0.0);
      g.lineTo(10.0, 0.0);
      g.lineTo(10.0, 0.0);
      g.lineTo(0.0, 0.0);
      g.lineTo(0.0, 0.0);
      g.lineTo(0.0, 10.0);
      g.lineTo(0.0, 290.0);
      g.lineTo(0.0, 300.0);
      g.lineTo(0.0, 310.0);
      g.lineTo(0.0, 590.0);
      g.lineTo(0.0, 600.0);
      g.lineTo(10.0, 600.0);
      g.lineTo(2100.0, 600.0);
      g.lineTo(2100.0, 590.0);
      g.lineTo(310.0, 590.0);
      g.lineTo(310.0, 500.0);
      g.lineTo(510.0, 500.0);
      g.lineTo(510.0, 490.0);
      g.lineTo(300.0, 490.0);
      g.lineTo(300.0, 500.0);
      g.lineTo(300.0, 590.0);
      g.lineTo(10.0, 590.0);
      g.lineTo(10.0, 310.0);
      g.lineTo(100.0, 310.0);
      g.lineTo(100.0, 500.0);
      g.lineTo(110.0, 500.0);
      g.lineTo(210.0, 500.0);
      g.lineTo(210.0, 490.0);
      g.lineTo(210.0, 400.0);
      g.lineTo(210.0, 390.0);
      g.lineTo(110.0, 390.0);
      g.lineTo(110.0, 310.0);
      g.lineTo(690.0, 310.0);
      g.lineTo(690.0, 500.0);
      g.lineTo(700.0, 500.0);
      g.lineTo(710.0, 500.0);
      g.lineTo(710.0, 310.0);
      g.lineTo(1000.0, 310.0);
      g.lineTo(1000.0, 500.0);
      g.lineTo(1010.0, 500.0);
      g.lineTo(1110.0, 500.0);
      g.lineTo(1110.0, 490.0);
      g.lineTo(1110.0, 400.0);
      g.lineTo(1110.0, 390.0);
      g.lineTo(1010.0, 390.0);
      g.lineTo(1010.0, 400.0);
      g.lineTo(1100.0, 400.0);
      g.lineTo(1100.0, 490.0);
      g.lineTo(1010.0, 490.0);
      g.lineTo(1010.0, 310.0);
      g.lineTo(1390.0, 310.0);
      g.lineTo(1390.0, 490.0);
      g.lineTo(1300.0, 490.0);
      g.lineTo(1300.0, 500.0);
      g.lineTo(1390.0, 500.0);
      g.lineTo(1400.0, 500.0);
      g.lineTo(1410.0, 500.0);
      g.lineTo(1410.0, 310.0);
      g.lineTo(1800.0, 310.0);
      g.lineTo(1800.0, 400.0);
      g.lineTo(1810.0, 400.0);
      g.lineTo(1810.0, 310.0);
      g.lineTo(2090.0, 310.0);
      g.lineTo(2090.0, 490.0);
      g.lineTo(2010.0, 490.0);
      g.lineTo(2010.0, 390.0);
      g.lineTo(2000.0, 390.0);
      g.lineTo(1910.0, 390.0);
      g.lineTo(1900.0, 390.0);
      g.lineTo(1900.0, 490.0);
      g.lineTo(1800.0, 490.0);
      g.lineTo(1800.0, 500.0);
      g.lineTo(1900.0, 500.0);
      g.lineTo(1910.0, 500.0);
      g.lineTo(1910.0, 400.0);
      g.lineTo(2000.0, 400.0);
      g.lineTo(2000.0, 490.0);
      g.lineTo(2000.0, 500.0);
      g.lineTo(2090.0, 500.0);
      g.lineTo(2100.0, 500.0);
      g.lineTo(2100.0, 310.0);
      g.lineTo(2100.0, 300.0);
      g.lineTo(2100.0, 290.0);
      g.lineTo(910.0, 290.0);
      g.lineTo(910.0, 190.0);
      g.lineTo(900.0, 190.0);
      g.lineTo(900.0, 290.0);
      g.lineTo(410.0, 290.0);
      g.lineTo(410.0, 200.0);
      g.lineTo(510.0, 200.0);
      g.lineTo(510.0, 190.0);
      g.lineTo(300.0, 190.0);
      g.lineTo(300.0, 200.0);
      g.lineTo(300.0, 290.0);
      g.lineTo(10.0, 290.0);
      g.lineTo(10.0, 10.0);
      g.lineTo(200.0, 10.0);
      g.lineTo(200.0, 90.0);
      g.lineTo(100.0, 90.0);
      g.lineTo(100.0, 100.0);
      g.lineTo(200.0, 100.0);
      g.lineTo(200.0, 190.0);
      g.lineTo(100.0, 190.0);
      g.lineTo(100.0, 200.0);
      g.lineTo(200.0, 200.0);
      g.lineTo(210.0, 200.0);
      g.lineTo(210.0, 10.0);
      g.lineTo(690.0, 10.0);
      g.lineTo(690.0, 200.0);
      g.lineTo(700.0, 200.0);
      g.lineTo(700.0, 200.0);
      g.lineTo(710.0, 200.0);
      g.lineTo(710.0, 10.0);
      g.lineTo(1390.0, 10.0);
      g.lineTo(1390.0, 200.0);
      g.lineTo(1400.0, 200.0);
      g.lineTo(1410.0, 200.0);
      g.lineTo(1410.0, 10.0);
      g.lineTo(1500.0, 10.0);
      g.lineTo(1500.0, 200.0);
      g.lineTo(1510.0, 200.0);
      g.lineTo(1510.0, 10.0);
      g.lineTo(2090.0, 10.0);
      g.lineTo(2090.0, 90.0);
      g.lineTo(2010.0, 90.0);
      g.lineTo(2000.0, 90.0);
      g.lineTo(2000.0, 190.0);
      g.lineTo(1810.0, 190.0);
      g.lineTo(1810.0, 100.0);
      g.lineTo(1910.0, 100.0);
      g.lineTo(1910.0, 90.0);
      g.lineTo(1810.0, 90.0);
      g.lineTo(1800.0, 90.0);
      g.lineTo(1800.0, 190.0);
      g.lineTo(1800.0, 200.0);
      g.lineTo(2090.0, 200.0);
      g.lineTo(2090.0, 200.0);
      g.lineTo(2100.0, 200.0);
      g.lineTo(2100.0, 10.0);
      g.lineTo(2100.0, 0.0);
      g.lineTo(2100.0, 0.0);
      g.lineTo(2090.0, 0.0);
      g.endFill();
      g.beginFill("#000");
      g.moveTo(200.0, 400.0);
      g.lineTo(200.0, 490.0);
      g.lineTo(110.0, 490.0);
      g.lineTo(110.0, 400.0);
      g.lineTo(200.0, 400.0);
      g.endFill();
      g.beginFill("#000");
      g.moveTo(310.0, 200.0);
      g.lineTo(400.0, 200.0);
      g.lineTo(400.0, 290.0);
      g.lineTo(310.0, 290.0);
      g.lineTo(310.0, 200.0);
      g.endFill();
      g.beginFill("#000");
      g.moveTo(2090.0, 190.0);
      g.lineTo(2010.0, 190.0);
      g.lineTo(2010.0, 100.0);
      g.lineTo(2090.0, 100.0);
      g.lineTo(2090.0, 190.0);
      return g.endFill();
    };

    LevelGameWindow.prototype.drawDoorsToCollisionMap = function() {
      var door, _i, _len, _ref, _results;
      this.collisionMap.graphics.clear();
      this.drawBaseCollisionMap(this.collisionMap.graphics);
      _ref = this.doors;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        door = _ref[_i];
        if (!door.isOpen) {
          this.collisionMap.graphics.beginFill("#000");
          this.collisionMap.graphics.drawRect(door.x, door.y, door.rectWidth, door.rectHeight);
          _results.push(this.collisionMap.graphics.endFill());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    LevelGameWindow.prototype.setupPedestalBitmap = function() {
      var overlayShape;
      this.pedestalBitmapLayer = new createjs.Container();
      this.pedestalBitmapLayer.addChild(new createjs.Bitmap(this.assetQueue.getResult("pedestals")));
      this.addChild(this.pedestalBitmapLayer);
      overlayShape = new createjs.Shape();
      overlayShape.graphics.beginFill("#000");
      overlayShape.graphics.drawRect(0, 0, 2100, 600);
      overlayShape.alpha = 0.05;
      return this.addChild(overlayShape);
    };

    LevelGameWindow.prototype.setupDoorLayer = function() {
      this.doorLayer = new createjs.Container();
      this.addDoorToLayer(new Door(100, 100, this, Door.COLOR_GREEN, true, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(200, 200, this, Door.COLOR_RED, false, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(400, 100, this, Door.COLOR_GREEN, true, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(500, 100, this, Door.COLOR_GREEN, true, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(500, 200, this, Door.COLOR_GREEN, true, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(100, 500, this, Door.COLOR_RED, false, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(500, 500, this, Door.COLOR_GREEN, false, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(900, 200, this, Door.COLOR_GREEN, false, Door.ORIENTATION_LANDSCAPE));
      this.addDoorToLayer(new Door(1000, 500, this, Door.COLOR_GREEN, false, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(1300, 500, this, Door.COLOR_BLUE, false, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(1500, 200, this, Door.COLOR_RED, false, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(1700, 200, this, Door.COLOR_BLUE, true, Door.ORIENTATION_LANDSCAPE));
      this.addDoorToLayer(new Door(1800, 200, this, Door.COLOR_GREEN, true, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(2000, 200, this, Door.COLOR_BLUE, false, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(1500, 500, this, Door.COLOR_RED, true, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(1600, 500, this, Door.COLOR_BLUE, false, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(1800, 500, this, Door.COLOR_GREEN, false, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(1800, 400, this, Door.COLOR_RED, false, Door.ORIENTATION_PORTRAIT));
      this.addDoorToLayer(new Door(1800, 400, this, Door.COLOR_RED, false, Door.ORIENTATION_LANDSCAPE));
      return this.addChild(this.doorLayer);
    };

    LevelGameWindow.prototype.addDoorToLayer = function(door) {
      this.doorLayer.addChild(door);
      return this.doors.push(door);
    };

    LevelGameWindow.prototype.setupPlayers = function() {
      this.topPlayer = new TopDimensionPlayer(this.collisionMap);
      this.topPlayer.x = 25;
      this.topPlayer.y = 220;
      this.bottomPlayer = new BottomDimensionPlayer(this.collisionMap);
      this.bottomPlayer.x = 25;
      this.bottomPlayer.y = 520;
      this.addChild(this.topPlayer);
      return this.addChild(this.bottomPlayer);
    };

    LevelGameWindow.prototype.setupForeground = function() {
      return this.addChild(new createjs.Bitmap(this.assetQueue.getResult("foreground")));
    };

    return LevelGameWindow;

  })(GameWindow);

}).call(this);
