// Generated by CoffeeScript 1.7.1
(function() {
  var FILENAMES, HEIGHT, WIDTH, preWin,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FILENAMES = ["foreground", "pedestals", "redOrb", "greenOrb", "blueOrb", "character", "xPlace", "xPickup", "zPlace", "zPickup"];

  WIDTH = 700;

  HEIGHT = 600;

  preWin = null;

  window.PreloaderGameWindow = (function(_super) {
    __extends(PreloaderGameWindow, _super);

    function PreloaderGameWindow() {
      return PreloaderGameWindow.__super__.constructor.apply(this, arguments);
    }

    PreloaderGameWindow.prototype.initialize = function() {
      var queue;
      PreloaderGameWindow.__super__.initialize.apply(this, arguments);
      preWin = this;
      queue = new createjs.LoadQueue();
      queue.loadFile({
        id: "logo",
        src: "/ld30/img/tbsh.png"
      });
      return queue.on("complete", this.startPreload);
    };

    PreloaderGameWindow.prototype.startPreload = function(e) {
      return preWin.setupProgressDisplay(e.target.getResult("logo"));
    };

    PreloaderGameWindow.prototype.setupProgressDisplay = function(logo) {
      var fadedLogo, loadingText, logoMatrix, progressLogo, progressText;
      fadedLogo = new createjs.Bitmap(logo);
      fadedLogo.regX = 75;
      fadedLogo.regY = 82;
      fadedLogo.x = WIDTH / 2;
      fadedLogo.y = HEIGHT / 2;
      this.addChild(fadedLogo);
      loadingText = new createjs.Text("Loading...", "20px Arial", "#000");
      loadingText.regX = loadingText.getMeasuredWidth() / 2;
      loadingText.regY = loadingText.getMeasuredHeight() / 2;
      loadingText.x = WIDTH / 2;
      loadingText.y = HEIGHT / 2 + 100;
      this.addChild(loadingText);
      progressLogo = new createjs.Shape();
      logoMatrix = new createjs.Matrix2D();
      logoMatrix.translate(WIDTH / 2 - 75, HEIGHT / 2 - 82);
      this.addChild(progressLogo);
      progressText = new createjs.Text("0%", "20px Arial", "#fff");
      progressText.regX = progressText.getMeasuredWidth() / 2;
      progressText.regY = progressText.getMeasuredHeight() / 2;
      progressText.x = WIDTH / 2 - 3;
      progressText.y = HEIGHT / 2 + 5;
      this.addChild(progressText);
      return Preloader.preload(FILENAMES, (function(e) {
        progressLogo.graphics.clear().beginBitmapFill(logo, "no-repeat", logoMatrix).drawRect(WIDTH / 2 - 75, HEIGHT / 2 - 82, 150 * e.progress, 165);
        progressText.text = "" + (Math.floor(e.progress * 100)) + "%";
        return progressText.regX = progressText.getMeasuredWidth() / 2;
      }), (function(e) {
        var loadedAssets;
        loadedAssets = e.target;
        preWin.game.setAssetQueue(loadedAssets);
        return preWin.game.setWindow(new LevelGameWindow(WIDTH, HEIGHT, loadedAssets));
      }));
    };

    return PreloaderGameWindow;

  })(GameWindow);

}).call(this);
