// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.GameWindow = (function(_super) {
    __extends(GameWindow, _super);

    function GameWindow(width, height) {
      this.width = width;
      this.height = height;
      this.initialize();
    }

    GameWindow.prototype.initialize = function() {
      return GameWindow.__super__.initialize.apply(this, arguments);
    };

    GameWindow.prototype.onTick = function() {};

    return GameWindow;

  })(createjs.Container);

}).call(this);
