// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BottomDimensionPlayer = (function(_super) {
    __extends(BottomDimensionPlayer, _super);

    function BottomDimensionPlayer(collisionMap) {
      BottomDimensionPlayer.__super__.constructor.call(this, collisionMap, null, 88);
    }

    return BottomDimensionPlayer;

  })(Player);

}).call(this);
