// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.TopDimensionPlayer = (function(_super) {
    __extends(TopDimensionPlayer, _super);

    function TopDimensionPlayer(collisionMap) {
      TopDimensionPlayer.__super__.constructor.call(this, collisionMap, null, 90);
    }

    return TopDimensionPlayer;

  })(Player);

}).call(this);
